import type { Product, User, Order } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    email: 'buyer@acmecorp.com',
    firstName: 'Sarah',
    lastName: 'Mitchell',
    companyName: 'Acme Corp',
    role: 'customer',
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'u2',
    email: 'procurement@globex.com',
    firstName: 'James',
    lastName: 'Patterson',
    companyName: 'Globex Industries',
    role: 'customer',
    createdAt: '2024-02-20T11:00:00Z',
  },
  // TODO: Manager users — add when building back-office screens
  {
    id: 'm1',
    email: 'admin@warehouse.com',
    firstName: 'Alex',
    lastName: 'Chen',
    companyName: 'WP Wholesale',
    role: 'manager',
    createdAt: '2023-11-01T08:00:00Z',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    sku: 'IND-GLOVE-NITRL-LG',
    name: 'Nitrile Industrial Gloves',
    description:
      'Heavy-duty nitrile gloves suitable for chemical handling, food processing, and general industrial use. Puncture-resistant with textured fingertips for superior grip. Powder-free formulation reduces contamination risk.',
    category: 'Safety & PPE',
    basePrice: 24.99,
    currency: 'USD',
    inventoryStatus: 'in_stock',
    stockQuantity: 4800,
    tags: ['gloves', 'ppe', 'nitrile', 'safety'],
    isActive: true,
    minOrderQuantity: 10,
    maxOrderQuantity: 500,
    deliveryEstimate: { minDays: 2, maxDays: 4, label: '2–4 business days' },
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-05-01T00:00:00Z',
    variantGroups: [
      {
        id: 'vg1',
        name: 'Size',
        required: true,
        options: [
          { id: 'vg1-s', label: 'Small', value: 'S', priceModifier: 0, stockQuantity: 1200, sku: 'IND-GLOVE-NITRL-SM' },
          { id: 'vg1-m', label: 'Medium', value: 'M', priceModifier: 0, stockQuantity: 1800, sku: 'IND-GLOVE-NITRL-MD' },
          { id: 'vg1-l', label: 'Large', value: 'L', priceModifier: 0, stockQuantity: 1200, sku: 'IND-GLOVE-NITRL-LG' },
          { id: 'vg1-xl', label: 'X-Large', value: 'XL', priceModifier: 1.5, stockQuantity: 600, sku: 'IND-GLOVE-NITRL-XL' },
        ],
      },
      {
        id: 'vg2',
        name: 'Package',
        required: true,
        options: [
          { id: 'vg2-100', label: 'Box of 100', value: '100', priceModifier: 0, stockQuantity: 2400, sku: 'IND-GLOVE-NITRL-B100' },
          { id: 'vg2-200', label: 'Box of 200', value: '200', priceModifier: 18.0, stockQuantity: 1200, sku: 'IND-GLOVE-NITRL-B200' },
        ],
      },
    ],
  },
  {
    id: 'p2',
    sku: 'CLEAN-DISINFECT-5L',
    name: 'Industrial Surface Disinfectant',
    description:
      'Hospital-grade disinfectant concentrate. Kills 99.99% of bacteria, viruses, and fungi. Effective against MRSA, C. difficile, and norovirus. Suitable for food-contact surfaces when properly diluted. 5-litre concentrated formula.',
    category: 'Cleaning & Hygiene',
    basePrice: 52.0,
    currency: 'USD',
    inventoryStatus: 'in_stock',
    stockQuantity: 960,
    tags: ['cleaning', 'disinfectant', 'hygiene', 'chemical'],
    isActive: true,
    minOrderQuantity: 4,
    maxOrderQuantity: 100,
    deliveryEstimate: { minDays: 3, maxDays: 5, label: '3–5 business days' },
    createdAt: '2024-01-12T00:00:00Z',
    updatedAt: '2024-04-28T00:00:00Z',
    variantGroups: [
      {
        id: 'vg3',
        name: 'Scent',
        required: false,
        options: [
          { id: 'vg3-unfrag', label: 'Unscented', value: 'unscented', priceModifier: 0, stockQuantity: 600, sku: 'CLEAN-DISINFECT-5L-UNF' },
          { id: 'vg3-citrus', label: 'Citrus', value: 'citrus', priceModifier: 2.0, stockQuantity: 360, sku: 'CLEAN-DISINFECT-5L-CIT' },
        ],
      },
    ],
  },
  {
    id: 'p3',
    sku: 'PAPER-A4-80GSM-CASE',
    name: 'A4 Copy Paper 80gsm',
    description:
      'Premium quality A4 copy paper, 80gsm. Acid-free for archival quality. Laser and inkjet compatible. Bright white finish for professional presentation. FSC certified sustainable sourcing.',
    category: 'Office Supplies',
    basePrice: 38.5,
    currency: 'USD',
    inventoryStatus: 'low_stock',
    stockQuantity: 120,
    tags: ['paper', 'office', 'printing', 'stationery'],
    isActive: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    deliveryEstimate: { minDays: 1, maxDays: 3, label: '1–3 business days' },
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-05-07T00:00:00Z',
    variantGroups: [
      {
        id: 'vg4',
        name: 'Quantity',
        required: true,
        options: [
          { id: 'vg4-5', label: '5 Reams (2,500 sheets)', value: '5-ream', priceModifier: 0, stockQuantity: 80, sku: 'PAPER-A4-80GSM-5R' },
          { id: 'vg4-10', label: '10 Reams (5,000 sheets)', value: '10-ream', priceModifier: 35.0, stockQuantity: 40, sku: 'PAPER-A4-80GSM-10R' },
        ],
      },
    ],
  },
  {
    id: 'p4',
    sku: 'HARDHAT-ANSI-WHTBL',
    name: 'ANSI Class E Hard Hat',
    description:
      'ANSI/ISEA Z89.1-2014 Type I, Class E certified. High-density polyethylene shell with 6-point suspension. Adjustable ratchet suspension (6.5"–8"). UV-stabilized. Suitable for electrical work up to 20,000 volts.',
    category: 'Safety & PPE',
    basePrice: 18.75,
    currency: 'USD',
    inventoryStatus: 'in_stock',
    stockQuantity: 2400,
    tags: ['hardhat', 'ppe', 'head protection', 'ansi'],
    isActive: true,
    minOrderQuantity: 5,
    maxOrderQuantity: 200,
    deliveryEstimate: { minDays: 2, maxDays: 3, label: '2–3 business days' },
    createdAt: '2024-01-18T00:00:00Z',
    updatedAt: '2024-04-15T00:00:00Z',
    variantGroups: [
      {
        id: 'vg5',
        name: 'Color',
        required: true,
        options: [
          { id: 'vg5-white', label: 'White', value: 'white', priceModifier: 0, stockQuantity: 800, sku: 'HARDHAT-ANSI-WHT' },
          { id: 'vg5-yellow', label: 'Yellow', value: 'yellow', priceModifier: 0, stockQuantity: 700, sku: 'HARDHAT-ANSI-YEL' },
          { id: 'vg5-blue', label: 'Blue', value: 'blue', priceModifier: 0, stockQuantity: 500, sku: 'HARDHAT-ANSI-BLU' },
          { id: 'vg5-orange', label: 'Orange', value: 'orange', priceModifier: 0, stockQuantity: 400, sku: 'HARDHAT-ANSI-ORG' },
        ],
      },
    ],
  },
  {
    id: 'p5',
    sku: 'TAPE-PACK-HEAVY-48MM',
    name: 'Heavy-Duty Packing Tape',
    description:
      'High-performance polypropylene packing tape. 48mm × 66m per roll. Acrylic adhesive bonds instantly to cardboard, plastic, and metal. Tear-resistant. Suitable for extreme temperatures (-30°C to +65°C).',
    category: 'Packaging & Shipping',
    basePrice: 3.2,
    currency: 'USD',
    inventoryStatus: 'in_stock',
    stockQuantity: 6000,
    tags: ['tape', 'packaging', 'shipping', 'packing'],
    isActive: true,
    minOrderQuantity: 24,
    maxOrderQuantity: 2000,
    deliveryEstimate: { minDays: 2, maxDays: 4, label: '2–4 business days' },
    createdAt: '2024-01-22T00:00:00Z',
    updatedAt: '2024-05-02T00:00:00Z',
    variantGroups: [
      {
        id: 'vg6',
        name: 'Pack Size',
        required: true,
        options: [
          { id: 'vg6-6', label: '6-Roll Pack', value: '6', priceModifier: 0, stockQuantity: 1500, sku: 'TAPE-PACK-HEAVY-6PK' },
          { id: 'vg6-24', label: '24-Roll Pack', value: '24', priceModifier: 10.8, stockQuantity: 1000, sku: 'TAPE-PACK-HEAVY-24PK' },
          { id: 'vg6-72', label: '72-Roll Pack', value: '72', priceModifier: 28.8, stockQuantity: 500, sku: 'TAPE-PACK-HEAVY-72PK' },
        ],
      },
    ],
  },
  {
    id: 'p6',
    sku: 'CAFPOD-OFFICE-MED-50',
    name: 'Office Coffee Pods — Medium Roast',
    description:
      'Fairtrade-certified 100% Arabica medium roast coffee pods. Compostable capsules. Compatible with Nespresso® Original Line machines. Smooth, balanced flavour with notes of caramel and toasted almond. 50-pod boxes.',
    category: 'Catering & Beverages',
    basePrice: 29.95,
    currency: 'USD',
    inventoryStatus: 'out_of_stock',
    stockQuantity: 0,
    tags: ['coffee', 'catering', 'beverages', 'office'],
    isActive: true,
    minOrderQuantity: 2,
    maxOrderQuantity: 100,
    deliveryEstimate: { minDays: 5, maxDays: 7, label: '5–7 business days' },
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-05-06T00:00:00Z',
    variantGroups: [
      {
        id: 'vg7',
        name: 'Roast',
        required: true,
        options: [
          { id: 'vg7-med', label: 'Medium', value: 'medium', priceModifier: 0, stockQuantity: 0, sku: 'CAFPOD-MED-50' },
          { id: 'vg7-dark', label: 'Dark', value: 'dark', priceModifier: 0, stockQuantity: 0, sku: 'CAFPOD-DARK-50' },
        ],
      },
    ],
  },
  {
    id: 'p7',
    sku: 'FORKLIFT-PAL-STRETCH-500M',
    name: 'Machine Stretch Wrap Film',
    description:
      'High-performance machine stretch wrap for pallet wrapping applications. 500mm × 300m per roll, 23-micron gauge. Pre-stretched for maximum efficiency. Clear film for barcode scanning. Compatible with standard turntable wrappers.',
    category: 'Packaging & Shipping',
    basePrice: 44.0,
    currency: 'USD',
    inventoryStatus: 'backordered',
    stockQuantity: 0,
    tags: ['stretch wrap', 'pallet', 'packaging', 'warehouse'],
    isActive: true,
    minOrderQuantity: 6,
    maxOrderQuantity: 144,
    deliveryEstimate: { minDays: 7, maxDays: 14, label: '7–14 business days (backordered)' },
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-05-05T00:00:00Z',
    variantGroups: [],
  },
  {
    id: 'p8',
    sku: 'FIRSTAID-KIT-HSE-50P',
    name: 'First Aid Kit — 50-Person Workplace',
    description:
      'HSE-compliant first aid kit for workplaces of up to 50 people. Contents: 1 guidance card, 20 × sterile plasters, 2 × sterile eye pads, 6 × triangular bandages, 6 × safety pins, 3 × medium dressings, 1 × large dressing, 3 × pairs nitrile gloves. Wall-mountable case.',
    category: 'Safety & PPE',
    basePrice: 67.5,
    currency: 'USD',
    inventoryStatus: 'in_stock',
    stockQuantity: 380,
    tags: ['first aid', 'safety', 'medical', 'compliance'],
    isActive: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
    deliveryEstimate: { minDays: 2, maxDays: 4, label: '2–4 business days' },
    createdAt: '2024-01-25T00:00:00Z',
    updatedAt: '2024-04-20T00:00:00Z',
    variantGroups: [],
  },
  {
    id: 'p9',
    sku: 'DESK-CHAIR-ERG-ADJ',
    name: 'Ergonomic Task Chair',
    description:
      'Fully adjustable ergonomic office chair. Lumbar support, adjustable armrests, seat height, and tilt tension. Breathable mesh back panel. 5-star nylon base with dual-wheel castors. BIFMA certified. Weight capacity: 150 kg.',
    category: 'Furniture & Equipment',
    basePrice: 289.0,
    currency: 'USD',
    inventoryStatus: 'in_stock',
    stockQuantity: 85,
    tags: ['chair', 'furniture', 'ergonomic', 'office'],
    isActive: true,
    minOrderQuantity: 1,
    maxOrderQuantity: 30,
    deliveryEstimate: { minDays: 5, maxDays: 10, label: '5–10 business days' },
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-05-01T00:00:00Z',
    variantGroups: [
      {
        id: 'vg8',
        name: 'Color',
        required: true,
        options: [
          { id: 'vg8-black', label: 'Black', value: 'black', priceModifier: 0, stockQuantity: 50, sku: 'DESK-CHAIR-ERG-BLK' },
          { id: 'vg8-grey', label: 'Grey', value: 'grey', priceModifier: 0, stockQuantity: 35, sku: 'DESK-CHAIR-ERG-GRY' },
        ],
      },
    ],
  },
  {
    id: 'p10',
    sku: 'MARKER-PERM-BLK-12PK',
    name: 'Permanent Markers — Black, 12-Pack',
    description:
      'Industrial-grade permanent markers with chisel tip. Fade-resistant, waterproof, and smear-proof ink. Works on cardboard, metal, plastic, glass, and fabric. Quick-drying, non-toxic. Ideal for warehouse labelling and inventory marking.',
    category: 'Office Supplies',
    basePrice: 8.99,
    currency: 'USD',
    inventoryStatus: 'low_stock',
    stockQuantity: 48,
    tags: ['markers', 'stationery', 'labelling', 'warehouse'],
    isActive: true,
    minOrderQuantity: 6,
    maxOrderQuantity: 200,
    deliveryEstimate: { minDays: 1, maxDays: 2, label: '1–2 business days' },
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-05-07T00:00:00Z',
    variantGroups: [],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord1',
    orderNumber: 'ORD-2024-0042',
    customerId: 'u1',
    status: 'delivered',
    currency: 'USD',
    subtotal: 748.5,
    totalAmount: 748.5,
    deliveryEstimate: { minDays: 2, maxDays: 4, label: '2–4 business days' },
    shippingAddress: '100 Industrial Way, Chicago, IL 60601',
    submittedAt: '2024-04-10T14:22:00Z',
    updatedAt: '2024-04-14T09:00:00Z',
    createdAt: '2024-04-10T14:22:00Z',
    items: [
      {
        id: 'oi1',
        productId: 'p1',
        productName: 'Nitrile Industrial Gloves',
        productSku: 'IND-GLOVE-NITRL-LG',
        quantity: 20,
        unitPrice: 24.99,
        lineTotal: 499.8,
        selectedVariants: [
          { variantGroupId: 'vg1', variantGroupName: 'Size', optionId: 'vg1-l', optionLabel: 'Large', priceModifier: 0 },
          { variantGroupId: 'vg2', variantGroupName: 'Package', optionId: 'vg2-100', optionLabel: 'Box of 100', priceModifier: 0 },
        ],
      },
      {
        id: 'oi2',
        productId: 'p8',
        productName: 'First Aid Kit — 50-Person Workplace',
        productSku: 'FIRSTAID-KIT-HSE-50P',
        quantity: 2,
        unitPrice: 67.5,
        lineTotal: 135.0,
        selectedVariants: [],
      },
      {
        id: 'oi3',
        productId: 'p5',
        productName: 'Heavy-Duty Packing Tape',
        productSku: 'TAPE-PACK-HEAVY-48MM',
        quantity: 24,
        unitPrice: 3.2,
        lineTotal: 76.8,
        selectedVariants: [
          { variantGroupId: 'vg6', variantGroupName: 'Pack Size', optionId: 'vg6-6', optionLabel: '6-Roll Pack', priceModifier: 0 },
        ],
      },
    ],
  },
  {
    id: 'ord2',
    orderNumber: 'ORD-2024-0067',
    customerId: 'u1',
    status: 'shipped',
    currency: 'USD',
    subtotal: 577.0,
    totalAmount: 577.0,
    deliveryEstimate: { minDays: 3, maxDays: 5, label: '3–5 business days' },
    shippingAddress: '100 Industrial Way, Chicago, IL 60601',
    submittedAt: '2024-04-28T10:05:00Z',
    updatedAt: '2024-05-03T08:30:00Z',
    createdAt: '2024-04-28T10:05:00Z',
    items: [
      {
        id: 'oi4',
        productId: 'p2',
        productName: 'Industrial Surface Disinfectant',
        productSku: 'CLEAN-DISINFECT-5L',
        quantity: 8,
        unitPrice: 52.0,
        lineTotal: 416.0,
        selectedVariants: [
          { variantGroupId: 'vg3', variantGroupName: 'Scent', optionId: 'vg3-unfrag', optionLabel: 'Unscented', priceModifier: 0 },
        ],
      },
      {
        id: 'oi5',
        productId: 'p4',
        productName: 'ANSI Class E Hard Hat',
        productSku: 'HARDHAT-ANSI-WHTBL',
        quantity: 8,
        unitPrice: 18.75,
        lineTotal: 150.0,
        selectedVariants: [
          { variantGroupId: 'vg5', variantGroupName: 'Color', optionId: 'vg5-yellow', optionLabel: 'Yellow', priceModifier: 0 },
        ],
      },
    ],
  },
  {
    id: 'ord3',
    orderNumber: 'ORD-2024-0081',
    customerId: 'u1',
    status: 'submitted',
    currency: 'USD',
    subtotal: 329.0,
    totalAmount: 329.0,
    deliveryEstimate: { minDays: 5, maxDays: 10, label: '5–10 business days' },
    shippingAddress: '100 Industrial Way, Chicago, IL 60601',
    submittedAt: '2024-05-07T16:45:00Z',
    updatedAt: '2024-05-07T16:45:00Z',
    createdAt: '2024-05-07T16:45:00Z',
    items: [
      {
        id: 'oi6',
        productId: 'p9',
        productName: 'Ergonomic Task Chair',
        productSku: 'DESK-CHAIR-ERG-ADJ',
        quantity: 1,
        unitPrice: 289.0,
        lineTotal: 289.0,
        selectedVariants: [
          { variantGroupId: 'vg8', variantGroupName: 'Color', optionId: 'vg8-black', optionLabel: 'Black', priceModifier: 0 },
        ],
      },
      {
        id: 'oi7',
        productId: 'p3',
        productName: 'A4 Copy Paper 80gsm',
        productSku: 'PAPER-A4-80GSM-CASE',
        quantity: 1,
        unitPrice: 38.5,
        lineTotal: 38.5,
        selectedVariants: [
          { variantGroupId: 'vg4', variantGroupName: 'Quantity', optionId: 'vg4-5', optionLabel: '5 Reams (2,500 sheets)', priceModifier: 0 },
        ],
      },
    ],
  },
];

export const PRODUCT_CATEGORIES = [
  'All',
  'Safety & PPE',
  'Cleaning & Hygiene',
  'Office Supplies',
  'Packaging & Shipping',
  'Catering & Beverages',
  'Furniture & Equipment',
];
